---
- name: normalize network state
  gather_facts: false
  hosts: test

  tasks:
    - name: create temporary working directory
      tempfile:
        state: directory
        suffix: root
        path: /tmp
      register: root_dir

    - name: create file to contain interfaces files and directories to be removed
      file:
        path: "{{ root_dir.path }}/iface_files_to_remove.txt"
        state: touch
        mode: '0644'
      register: iface_files_to_remove

    - name: remove listed filepaths
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ files_to_delete.stdout_lines }}"

    - name: disable spd service
      lineinfile: 
        path: "{{ task_execution_file.dest }}"
        line: "systemctl disable iep-spd.service"
        state: present
        backup: no
      register: execute_task

    - name: get interfaces file path
      find: 
        path: /etc/network
        patterns: "interfaces*"
        file_type: file
      register: interfaces_path

    - name: append filepaths to removal manifest 
      lineinfile:
        path: "{{ files_to_remove.dest }}"
        line: "{{ item.path }}"
        state: present
        backup: no
      with_items: "{{ interfaces_path.files }}"

    ---
    - name: run commit module
      commit:
        files: {"removal_manifest": "{{ files_to_remove.dest }}", 
                "command_execution": "{{ command_execution_file.dest }}"}
        source: "{{ workdir_path }}/etc/"
        dest: "/etc/"
      register: output


