---

- name: IEP adoption
  gather_facts: false
  hosts: "@3d-p/insight/v1/device/3d-p/iep"

  tasks:
    - name: Make filesystem writeable
      command: rw

    - name: Install ThingID
      copy:
        content: "{{ thing_id }}\n"
        dest: "/etc/3d-p/thingybits/thing_id"
        force: true

    - name: Make filesystem non-writeable
      command: ro
